//Links
export const DOCS_URL = 'https://docs.wetrocloud.com'
export const CONSOLE_URL = 'https://console.wetrocloud.com'
export const BOOK_CALL_URL = 'https://cal.com/divinejoshua/wetrocloud-demo'
export const DOCS_RAG_API_URL = 'https://docs.wetrocloud.com/endpoint-explanations/create'
export const API_REFERENCES_URL = 'https://docs.wetrocloud.com/api-references'
export const LINKEDIN_URL = 'https://www.linkedin.com/company/wetrocloud'
export const REGISTER_DEVELOPER_URL = 'https://console.wetrocloud.com/auth?type=developer'
export const REGISTER_STARTUP_URL = 'https://console.wetrocloud.com/auth?type=startup'
export const REGISTER_ENTERPRISE_URL = 'https://console.wetrocloud.com/auth?type=enterprise'