//Links
export const DOCS_URL = 'https://docs.wetrocloud.com'
export const CONSOLE_URL = 'https://console.wetrocloud.com'
export const BOOK_CALL_URL = 'https://cal.com/divinejoshua/wetrocloud-demo'
export const DOCS_RAG_API_URL = 'https://docs.wetrocloud.com/endpoint-explanations/create'
export const DOCS_QUICK_START_URL = 'https://docs.wetrocloud.com/quickstart'
export const DOCS_DATA_EXTRACTION_URL = 'https://docs.wetrocloud.com/quickstart'
export const DOCS_IMAGE_TO_TEXT_URL = "https://docs.wetrocloud.com/endpoint-explanations/image-to-text"
export const DOCS_TEXT_GENERATION_API_URL = 'https://docs.wetrocloud.com/endpoint-explanations/text-generation'
export const API_REFERENCES_URL = 'https://docs.wetrocloud.com/api-references'
export const LINKEDIN_URL = 'https://www.linkedin.com/company/wetrocloud'
export const REGISTER_DEVELOPER_URL = 'https://console.wetrocloud.com/auth?type=developer'
export const REGISTER_STARTUP_URL = 'https://console.wetrocloud.com/auth?type=startup'
export const REGISTER_ENTERPRISE_URL = 'https://console.wetrocloud.com/auth?type=enterprise'
export const BLOG_URL = 'https://medium.com/@wetrocloud'
export const PRIVACY_POLICY_URL = '/legal/privacy-policy'
export const TERMS_OF_SERVICE_URL = '/legal/terms-of-service'